### ISSUE TITLE
rails generate refinery:bootstrap

### ISSUE THREAD

**Issue by kfn8dkodemonkey** [fernandoaleman/refinerycms-bootstrap#1]
not sure what I have done wrong. I am running  refinery 2.1.0 
I have tried to in state your gem however when I run rails generate refinery:bootstrap I get the following error: 
/home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinery/bootstrap/engine.rb:4:
in `<class:Engine>': uninitialized constant Refinery::Engine (NameError)
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinery/bootstrap
/engine.rb:3:in`module:Bootstrap'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinery/bootstrap
/engine.rb:2:in `<module:Refinery>'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinery/bootstrap
/engine.rb:1:in`<top (required)>'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinery/bootstrap
.rb:7:in `require'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinery/bootstrap
.rb:7:in`module:Bootstrap'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinery/bootstrap
.rb:6:in `<module:Refinery>'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinery/bootstrap
.rb:3:in`<top (required)>'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinerycms-bootst
rap.rb:1:in `require'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/bundler/gems/refinerycms-bootstrap-b90e39e106ab/lib/refinerycms-bootst
rap.rb:1:in`<top (required)>'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.5.2/lib/bundler/runtime.rb:76:in `require'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.5.2/lib/bundler/runtime.rb:76:in`block (2 levels) in r
equire'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.5.2/lib/bundler/runtime.rb:72:in `each'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.5.2/lib/bundler/runtime.rb:72:in`block in require'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.5.2/lib/bundler/runtime.rb:61:in `each'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.5.2/lib/bundler/runtime.rb:61:in`require'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.5.2/lib/bundler.rb:131:in `require'
        from /home/kodemonkey/Dev/Templates/RefineryCMS/config/application.rb:7:in`<top (required)>'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/railties-3.2.13/lib/rails/commands.rb:53:in `require'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/railties-3.2.13/lib/rails/commands.rb:53:in`block in <top (requi
red)>'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/railties-3.2.13/lib/rails/commands.rb:50:in `tap'
        from /home/kodemonkey/.rvm/gems/ruby-2.0.0-p353/gems/railties-3.2.13/lib/rails/commands.rb:50:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'

Any help is great.

Thank you 
Heather ~ The Kode Monkey

**Comment by combusean** [comment]
I was getting this same issue until I put `gem 'refinerycms-bootstrap', :github => 'fernandoaleman/refinerycms-bootstrap', :branch => '2-1-stable'` below `gem 'refinerycms', '~> 2.1.0'` in the Gemfile.
